CREATE TABLE prompt_folders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL UNIQUE,
  description VARCHAR2(500),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE prompts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id NUMBER REFERENCES prompt_folders(id) ON DELETE SET NULL,
  title VARCHAR2(180) NOT NULL,
  body CLOB NOT NULL,
  summary VARCHAR2(500),
  tags VARCHAR2(800),
  variables VARCHAR2(800),
  favorite NUMBER(1) DEFAULT 0 NOT NULL CHECK (favorite IN (0, 1)),
  last_used_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE prompt_optimizations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt_id NUMBER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
  original_body CLOB NOT NULL,
  optimized_body CLOB NOT NULL,
  notes CLOB,
  provider VARCHAR2(80) DEFAULT 'deepseek' NOT NULL,
  model_name VARCHAR2(120),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_prompts_folder ON prompts(folder_id);
CREATE INDEX idx_prompts_updated_at ON prompts(updated_at);
CREATE INDEX idx_prompt_optimizations_prompt ON prompt_optimizations(prompt_id);

INSERT INTO prompt_folders (name, description)
VALUES ('General Prompts', 'Reusable writing, analysis, and summary prompts.');

INSERT INTO prompt_folders (name, description)
VALUES ('Developer Assistant', 'Code generation, debugging, review, and architecture prompts.');

INSERT INTO prompts (folder_id, title, body, summary, tags, variables, favorite)
SELECT id,
       'Code Review Prompt',
       'Act as a senior engineer and review the following code. Prioritize correctness, security, performance, and maintainability. Sort findings by severity and include concrete file or line suggestions when available. Code: {{code}}',
       'Structured prompt for AI-assisted code review.',
       'development,review,quality',
       'code',
       1
FROM prompt_folders
WHERE name = 'Developer Assistant';

INSERT INTO prompts (folder_id, title, body, summary, tags, variables, favorite)
SELECT id,
       'Chinese Summary Prompt',
       'Summarize the following content in Chinese. Preserve key facts, numbers, decisions, and action items. Content: {{content}}',
       'Turns long text into a clear Chinese summary.',
       'writing,summary,chinese',
       'content',
       0
FROM prompt_folders
WHERE name = 'General Prompts';

COMMIT;
